input_path: /mnt/d/Projects/dataset/demo_img
output_path: /mnt/d/Projects/dataset/output_img

model:
  config_file: src/models/segformer_mit-b4_8xb2-160k_ade20k-512x512.py
  checkpoint_file: src/models/segformer_mit-b4_512x512_160k_ade20k_20210728_183055-7f509d7d.pth
  device: cuda:0